import LegalLayout from "@/components/LegalLayout";

const sections = [
  {
    heading: "Summary of Key Points",
    body: 'What personal information do we process? When you visit, use, or navigate our Services, we may process personal information depending on how you interact with us and the Services, the choices you make, and the products and features you use.\n\nDo we process any sensitive personal information? We do not process sensitive personal information.\n\nDo we collect any information from third parties? We do not collect any information from third parties.\n\nHow do we process your information? We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law.\n\nIn what situations and with which parties do we share personal information? We may share information in specific situations and with specific third parties. Learn more in section 4 below.\n\nHow do we keep your information safe? We have adequate organizational and technical processes and procedures in place to protect your personal information. However, no electronic transmission over the internet or information storage technology can be guaranteed to be 100% secure.\n\nWhat are your rights? Depending on where you are located geographically, the applicable privacy law may mean you have certain rights regarding your personal information.\n\nHow do you exercise your rights? Contact us at privacy@boltsapp.app. We will consider and act upon any request in accordance with applicable data protection laws.',
  },
  {
    heading: "1. What Information Do We Collect?",
    body: "We collect personal information that you voluntarily provide to us when you register on the Services, express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.\n\nPersonal information we collect includes: names and email addresses.\n\nWe do not process sensitive personal information.\n\nIf you use our application, we may also collect the following information if you choose to provide us with access or permission:\n\nPush Notifications. We may request to send you push notifications regarding your account or certain features of the application. If you wish to opt out from receiving these types of communications, you may turn them off in your device's settings.\n\nPurchase and Transaction Data. Payment for the app is processed entirely by the Apple App Store or Google Play Store. We receive confirmation of your transaction and purchase status but do not collect or store payment card information.\n\nAll personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.\n\nGoogle API: Our use of information received from Google APIs will adhere to Google API Services User Data Policy, including the Limited Use requirements.",
  },
  {
    heading: "2. How Do We Process Your Information?",
    body: "We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes only with your prior explicit consent.\n\nWe process your personal information for the following purposes:\n\nTo facilitate account creation and authentication and otherwise manage user accounts. We may process your information so you can create and log in to your account, as well as keep your account in working order.\n\nTo deliver and facilitate delivery of services to the user. We may process your information to provide you with the requested service.\n\nTo save or protect an individual's vital interest. We may process your information when necessary to save or protect an individual's vital interest, such as to prevent harm.",
  },
  {
    heading: "3. What Legal Bases Do We Rely On to Process Your Information?",
    body: "We only process your personal information when we believe it is necessary and we have a valid legal reason to do so under applicable law, such as with your consent, to comply with laws, to provide you with services or fulfill our contractual obligations, to protect your rights, or to fulfill our legitimate business interests.\n\nIf you are located in the EU or UK: The GDPR and UK GDPR require us to explain the valid legal bases we rely on. We may rely on the following: Consent (you can withdraw at any time); Performance of a Contract (to fulfill our contractual obligations to you); Legal Obligations (compliance with applicable law); and Vital Interests (to protect your or a third party's vital interests).\n\nIf you are located in Canada: We may process your information if you have given us specific permission (express consent) or where your permission can be inferred (implied consent). You can withdraw your consent at any time. In some exceptional cases, we may be legally permitted to process your information without consent as permitted under applicable Canadian law.",
  },
  {
    heading: "4. When and With Whom Do We Share Your Personal Information?",
    body: "We may need to share your personal information in the following situations:\n\nBusiness Transfers. We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.",
  },
  {
    heading: "5. How Long Do We Keep Your Information?",
    body: "We keep your personal information for as long as it is necessary for the purposes set out in this Privacy Notice, unless a longer retention period is required or permitted by law. No purpose in this notice will require us keeping your personal information for longer than the period of time in which users have an account with us.\n\nWhen we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.",
  },
  {
    heading: "6. How Do We Keep Your Information Safe?",
    body: "We have implemented appropriate and reasonable technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals, or other unauthorized third parties will not be able to defeat our security and improperly collect, access, steal, or modify your information. Although we will do our best to protect your personal information, transmission of personal information to and from our Services is at your own risk. You should only access the Services within a secure environment.",
  },
  {
    heading: "7. Do We Collect Information From Minors?",
    body: "We do not knowingly collect, solicit data from, or market to children under 18 years of age, nor do we knowingly sell such personal information. By using the Services, you represent that you are at least 18 years of age, or that you are the parent or guardian of a minor and consent to such minor's use of the Services.\n\nIf we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we may have collected from children under age 18, please contact us at privacy@boltsapp.app.",
  },
  {
    heading: "8. What Are Your Privacy Rights?",
    body: "Depending on your state of residence in the US or in some regions, such as the European Economic Area (EEA), United Kingdom (UK), Switzerland, and Canada, you have rights that allow you greater access to and control over your personal information.\n\nIn some regions (like the EEA, UK, Switzerland, and Canada), you have certain rights under applicable data protection laws. These may include the right (i) to request access and obtain a copy of your personal information, (ii) to request rectification or erasure, (iii) to restrict the processing of your personal information, (iv) if applicable, to data portability, and (v) not to be subject to automated decision-making. You can make such a request by contacting us at privacy@boltsapp.app.\n\nWithdrawing your consent: If we are relying on your consent to process your personal information, you have the right to withdraw your consent at any time by contacting us at privacy@boltsapp.app. Please note that this will not affect the lawfulness of the processing before its withdrawal.\n\nAccount Information: If you would at any time like to review or change the information in your account or terminate your account, you can log in to your account settings and update your user account. Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, we may retain some information in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our legal terms, and/or comply with applicable legal requirements.\n\nIf you have questions or comments about your privacy rights, you may email us at privacy@boltsapp.app.",
  },
  {
    heading: "9. Controls for Do-Not-Track Features",
    body: 'Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track ("DNT") feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. At this stage, no uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this Privacy Notice.\n\nCalifornia law requires us to let you know how we respond to web browser DNT signals. Because there currently is not an industry or legal standard for recognizing or honoring DNT signals, we do not respond to them at this time.',
  },
  {
    heading: "10. Do United States Residents Have Specific Privacy Rights?",
    body: "If you are a resident of California, Colorado, Connecticut, Delaware, Florida, Indiana, Iowa, Kentucky, Maryland, Minnesota, Montana, Nebraska, New Hampshire, New Jersey, Oregon, Rhode Island, Tennessee, Texas, Utah, or Virginia, you may have the right to request access to and receive details about the personal information we maintain about you, correct inaccuracies, get a copy of, or delete your personal information. You may also have the right to withdraw your consent to our processing of your personal information.\n\nCategories of Personal Information We Collect: We collect the following categories of personal information as defined by state privacy laws: identifiers (name and email address provided at registration) and commercial information (record of app purchase transaction). We do not collect: protected classification characteristics, biometric information, internet or network activity, geolocation data, audio or sensory information, professional or employment-related information, education information, inferences drawn from personal information, or sensitive personal information.\n\nYour rights include: Right to know whether or not we are processing your personal data; Right to access your personal data; Right to correct inaccuracies in your personal data; Right to request the deletion of your personal data; Right to obtain a copy of the personal data you previously shared with us; Right to non-discrimination for exercising your rights; Right to opt out of the processing of your personal data if it is used for targeted advertising, the sale of personal data, or profiling.\n\nHow to Exercise Your Rights: Contact us by emailing privacy@boltsapp.app. Under certain US state data protection laws, you can designate an authorized agent to make a request on your behalf. If your appeal is denied, you may submit a complaint to your state attorney general.\n\nWe have not disclosed, sold, or shared any personal information to third parties for a business or commercial purpose in the preceding twelve (12) months. We will not sell or share personal information in the future belonging to website visitors, users, and other consumers.\n\nCalifornia \"Shine The Light\" Law: California Civil Code Section 1798.83 permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes. To make such a request, please contact us at privacy@boltsapp.app.",
  },
  {
    heading: "11. Do We Make Updates to This Notice?",
    body: 'Yes, we will update this notice as necessary to stay compliant with relevant laws. We may update this Privacy Notice from time to time. The updated version will be indicated by an updated "Last updated" date at the top of this Privacy Notice. If we make material changes to this Privacy Notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this Privacy Notice frequently to be informed of how we are protecting your information.',
  },
  {
    heading: "12. How Can You Contact Us About This Notice?",
    body: "If you have questions or comments about this notice, you may email us at privacy@boltsapp.app.",
  },
  {
    heading: "13. How Can You Review, Update, or Delete the Data We Collect From You?",
    body: "Based on the applicable laws of your country or state of residence in the US, you may have the right to request access to the personal information we collect from you, details about how we have processed it, correct inaccuracies, or delete your personal information. You may also have the right to withdraw your consent to our processing of your personal information. These rights may be limited in some circumstances by applicable law. To request to review, update, or delete your personal information, please contact us at privacy@boltsapp.app.",
  },
];

export default function PrivacyPage() {
  return (
    <LegalLayout
      title="Privacy Policy"
      effectiveDate="June 11, 2026"
      intro={'This Privacy Notice for Justin Adam Leggett ("we," "us," or "our") describes how and why we might access, collect, store, use, and/or share ("process") your personal information when you use our services ("Services"), including when you download and use our mobile application (BOLTS). BOLTS is a mobile application for skateboarders that helps users track their progress learning skateboarding tricks. The app provides a curated directory of skateboarding tricks and allows users to mark each trick as not started, in progress, or completed. Users can also add their own custom tricks, log practice sessions with attempt counts and notes, and monitor their overall progress. BOLTS requires users to create an account using an email address and display name. BOLTS is available as a one-time paid purchase through the Apple App Store or Google Play Store. Questions or concerns? Contact us at privacy@boltsapp.app.'}
      sections={sections}
    />
  );
}
